-- Beginner:
-- Q1. What are the top 5 countries with the highest number of confirmed cases?
-- Q2. Which WHO region has the highest number of total deaths?
-- Q3. How many new deaths were reported in the last week for each country/region?
-- Q4. What percentage of the confirmed cases are active cases for each country/region?
-- Q5. Which WHO region has the highest number of recovered cases?
-- Q6. How does the total number of deaths this week compare to the total number of deaths last week for each country/region?
-- Q7. What is the total number of new cases reported in the last week across all countries/regions?
-- Q8. How many countries/regions reported zero new deaths this week?
-- Q9. Which WHO region has the lowest number of confirmed cases?
-- Q10. What is the total number of recoveries for countries/regions with fewer than 1,000 confirmed cases?
-- Intermediate:
-- Q11. What is the average number of new cases reported per country/region?
-- Q12.	Which country/region experienced the largest increase in confirmed cases from last week to this week?
-- Q13.	What percentage of the confirmed cases are active cases for each country/region?
-- Q14.	What is the average number of deaths reported per WHO region?
-- Q15.	Which country/region has the highest number of active cases?
-- Q16.	What is the total number of new deaths reported by each WHO region?
-- Q17.	How many countries/regions reported zero new deaths this week?
-- Q18.	What is the average number of new cases reported in the top 5 WHO regions?
-- Q19.	How many new recoveries were reported this week compared to last week for each country/region?
-- Q20.	What is the total number of active cases reported in the bottom 10 countries/regions by confirmed cases?
-- Advanced:
-- Q21.	What is the total number of confirmed cases in the top 3 countries/regions with the highest number of confirmed cases?
-- Q22.	Which country/region has the highest new recovery rate (percentage of new recoveries out of new cases)?
-- Q23.	What is the average change in confirmed cases for the top 10 countries/regions?
-- Q24.	Which country/region saw the most significant decrease in active cases from last week to this week?
-- Q25.	What is the total number of confirmed cases and deaths combined for each country/region, and which country/region has the highest total?

